<div class="news-wrapper">
    <div class="news-global-title">
        <p>FROM FASHION WORLD</p>
        <div class="news-underline"></div>
    </div>
    <div class="slider theme_background">
        <div data-mage-init="{'home2':{}}">
    <div class="news-miniblock-wrapper slider__base">
        <div class="news-container">
            <div class="news-image-block"></div>
            <div class="news-text">
                <div class="news-date">Posted 25 August</div>
                <div class="news-title">REVEAL THE BRAND SHOPPING STRATEGY</div>
                <div class="read-more">READ MORE<img src="{{media url="wysiwyg/home/arrow-forward-outline.png"}}" alt="" class="read-more-arrow"></div>
            </div>
        </div>
        <div class="news-container">
            <div class="news-image-block"></div>
            <div class="news-text">
                <div class="news-date">Posted 25 August</div>
                <div class="news-title">MOST EXPENSIVE DRESS IN SHOWBIZ HISTORY</div>
                <div class="read-more">READ MORE<img src="{{media url="wysiwyg/home/arrow-forward-outline.png"}}" alt="" class="read-more-arrow"></div>
            </div>
        </div>
    </div>
            <div class="news-miniblock-wrapper slider__base">
                <div class="news-container">
                    <div class="news-image-block"></div>
                    <div class="news-text">
                        <div class="news-date">Posted 25 August</div>
                        <div class="news-title">REVEAL THE BRAND SHOPPING STRATEGY</div>
                        <div class="read-more">READ MORE<img src="{{media url="wysiwyg/home/arrow-forward-outline.png"}}" alt="" class="read-more-arrow"></div>
                    </div>
                </div>
                <div class="news-container">
                    <div class="news-image-block"></div>
                    <div class="news-text">
                        <div class="news-date">Posted 25 August</div>
                        <div class="news-title">MOST EXPENSIVE DRESS IN SHOWBIZ HISTORY</div>
                        <div class="read-more">READ MORE<img src="{{media url="wysiwyg/home/arrow-forward-outline.png"}}" alt="" class="read-more-arrow"></div>
                    </div>
                </div>
            </div>
            <div class="news-miniblock-wrapper slider__base">
                <div class="news-container">
                    <div class="news-image-block"></div>
                    <div class="news-text">
                        <div class="news-date">Posted 25 August</div>
                        <div class="news-title">REVEAL THE BRAND SHOPPING STRATEGY</div>
                        <div class="read-more">READ MORE<img src="{{media url="wysiwyg/home/arrow-forward-outline.png"}}" alt="" class="read-more-arrow"></div>
                    </div>
                </div>
                <div class="news-container">
                    <div class="news-image-block"></div>
                    <div class="news-text">
                        <div class="news-date">Posted 25 August</div>
                        <div class="news-title">MOST EXPENSIVE DRESS IN SHOWBIZ HISTORY</div>
                        <div class="read-more">READ MORE<img src="{{media url="wysiwyg/home/arrow-forward-outline.png"}}" alt="" class="read-more-arrow"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>