<div class="banner-wrapper">
    <div class="slider theme_background">
        <div data-mage-init="{"home2":{}}">
        <div class="slider__base"><img class="banner-slide" src="{{media url="wysiwyg/home/a29b84af25b2389b9a087249cd35173a.jpg"}}" alt="">
            <p class="slider-text">1 of 3</p>
        </div>
        <div class="slider__base"><img class="banner-slide" src="{{media url="wysiwyg/home/ee4603ebe969881abe35adaf2d78e7f0.jpg"}}" alt="">
            <p class="slider-text">2 of 3</p>
        </div>
        <div class="slider__base"><img class="banner-slide" src="{{media url="wysiwyg/home/banner_design.png"}}" alt="">
            <p class="slider-text">3 of 3</p>
        </div>
    </div>
</div>
</div>