<div class="collection-wrapper">
    <div class="image-block"></div>
    <div class="collection-text">
        <p class="collection-title-1">The Hot Collection</p>
        <p class="collection-title-2">SUMMER SALE</p>
        <p class="collection-description">Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque soluta, nihil ipsa delectus qui temporibus minima voluptate suscipit error quae rem.</p>
        <p class="bg-decoration">SUMMER</p>
        <a class="collection-shop-button">SHOP NOW <img src="{{media url="wysiwyg/home/arrow-forward-outline.png"}}" alt="" class="collection-arrow-icon"></a></div>
</div>