<div class="collection-wrapper-2">
    <div class="collection-text">
        <p class="collection-title-1">Stylish &amp; Trendy</p>
        <p class="collection-title-2">BAGS AND ACCESSORIES</p>
        <p class="collection-description">Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque soluta, nihil ipsa delectus qui temporibus minima voluptate suscipit error quae rem.</p>
        <p class="bg-decoration-2">FASHION</p>
        <a class="collection-shop-button">SHOP NOW <img src="{{media url="wysiwyg/home/arrow-forward-outline.png"}}" alt="" class="collection-arrow-icon"></a></div>
    <div class="image-block-2"></div>
</div>