<div class="subscription-wrapper">
    <p class="subscription-title">GET THE LATEST ITEMS FROM STORENIX</p>
    <p class="subscription-description">Subscribe to our Newsletter &amp; WIN Great Prizes</p>
    {{block class="Magento\Newsletter\Block\Subscribe" name="static.newsletter" template="Magento_Newsletter::subscribe.phtml"}}</div>
<div class="my-footer-wrapper">
    <div class="footer-content-wrapper"><img src="{{media url="wysiwyg/home/logo.png"}}" alt="">
        <div class="my-footer-underline"></div>
        <div class="my-footer-address">{{config path="general/store_information/street_line1"}} | {{config path="general/store_information/phone"}} | {{config path="trans_email/ident_custom1/email"}}</div>
        <div class="footer-categories"><a href="#">Home</a><a href="#">Categories</a><a href="#">Shop</a><a href="#">Pages</a><a href="#">About</a><a href="#">Contact</a></div>
        <div class="social-networks"><i class="fab fa-facebook-f"></i> <i class="fab fa-vimeo-v"></i> <i class="fab fa-google-plus-g"></i> <i class="fab fa-twitter"></i> <i class="fab fa-pinterest-p"></i> <i class="fab fa-youtube"></i></div>
    </div>
</div>