<div class="offers-wrapper">
    <div class="offers-container"><img src="<?= $block->getViewFileUrl('images/bus-icon.png'); ?>" alt="" class="logo">
        <div class="offers-text">
            <p class="offers-title">FREE DELIVERY WORLDWIDE</p>
            <p class="offers-details">On all orders over $500</p>
        </div>
    </div>
    <div class="offers-container"><img src="<?= $block->getViewFileUrl('images/arrow-icon.png'); ?>" alt="" class="logo">
        <div class="offers-text">
            <p class="offers-title">FLEXIBLE RETURN POLICY</p>
            <p class="offers-details">If ordered items damaged</p>
        </div>
    </div>
    <div class="offers-container"><img src="<?= $block->getViewFileUrl('images/money-icon.png'); ?>" alt="" class="logo">
        <div class="offers-text">
            <p class="offers-title">SECURE PAYMENT GATEWAY</p>
            <p class="offers-details">100% secured merchant</p>
        </div>
    </div>
</div>