<div class="trends-wrapper">
    <div class="trend-wrapper-1">
        <div class="mini-block-1"></div>
        <p class="trend-title-1">SUMMER SHOES <img src="{{media url="wysiwyg/home/arrow-forward-outline.png"}}" alt="" class="trends-arrow-icon"></p>
    </div>
    <div class="trend-wrapper-2">
        <div class="mini-block-2"></div>
        <p class="trend-title-2">NEW TRENDS <img src="{{media url="wysiwyg/home/arrow-forward-outline.png"}}" alt="" class="trends-arrow-icon"></p>
    </div>
</div>